### ISSUE TITLE
Unable to use TestServerBuilder for Unit Testing

### ISSUE THREAD

**Issue by bishopsheen** [graphql-aspnet/graphql-aspnet#117]
I have added the project graphql-aspnet-testframework to my solution and removed the project reference to graphql-aspnet.  I have added a package reference to GraphQL.AspNet.  Once I have removed the project reference to graphql-aspnet and added the package reference to GraphQL.AspNet, I get an error when compiling graphql-aspnet-testframework "'InputArgumentCollection' is inaccessible due to its protection level".  InputArgumentCollection is now designated as an internal class whereas it used to be a public class.  Now that this is internal, it is unavailable to graphql-aspnet-testframework when you remove the project reference to graphql-aspnet.

Can this be changed back to public instead of internal so that we can continue to use the graphql-aspnet-framework within our solution?

**Comment by kevin-carroll** [comment]
Hey @bishopsheen ,

This is definitely an oversight on my part.  `InputArgumentCollection` was made internal about 6 months ago just before `v1.0` was released in an effort to reduce the public implementation footprint. A new mockable interface `IInputArgumentCollection` was added to allow for better unit testing of field execution contexts without forcing reliance on a strict implementation. The irony in the fact that the unit test framework was impacted as a result is a bit on the nose. :)  Thank you for calling it out.

I'll get the test framework cleaned up such that it can be used in isolation with the next release.  The class won't be made public but I will propagate the interface appropriately to clear the dependency issue.

Cheers,
Kevin

**Comment by bishopsheen** [comment]
Kevin,

Thanks for looking at this.  This package has been great, we started our schema with 0.6 and have been expanding it ever since.

Thanks,
Chris Burns

Sent via the Samsung Galaxy A32 5G, an AT&T 5G smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by bishopsheen** [comment]
Kevin,

   I have been using the TestServerBuilder in my schema integration tests.  I primarily have these integration tests in place for each parameter field that can be passed into the query.  We have completed a couple of major refactorings and this has saved us a lot of time running these integration tests to see if or where we broke the existing schema.

Thanks,
Chris
________________________________
