### ISSUE TITLE
Controller inheritance not working with Multi-Schema

### ISSUE THREAD

**Issue by sergiocbueno** [graphql-aspnet/graphql-aspnet#121]
Hi,

One of my projects is using Multi-Schema and controllers with inheritance, however, the base controller endpoints are not available/exposed. Follow more technical details below.

As you can see one of my base controllers inherits from _BaseGraphqlController_ which is a mandatory requirement (your documentation).
![image](https://github.com/graphql-aspnet/graphql-aspnet/assets/46008407/61e9d174-c829-4658-8739-262d4fb06bd7)

Then another controller inherits the one above.
![image](https://github.com/graphql-aspnet/graphql-aspnet/assets/46008407/4034ff97-798f-429e-bcd7-eb5d5255e3ac)

Also, follow my dependency injection setting of Multi-Schema for the controller above.
![image](https://github.com/graphql-aspnet/graphql-aspnet/assets/46008407/2465d167-cb01-419e-918c-674a31ffe5de)

Now when I try to call the endpoints I can **NOT** access the base ones, as you can see in the screenshot below:
![image](https://github.com/graphql-aspnet/graphql-aspnet/assets/46008407/5c338d72-cb5c-4de7-af5a-8097166b06fb)

I've already tried many options, including setting up the GraphRoute, GraphRoot, Query, and QueryRoot between the controllers (including the base ones). Still, all options failed and I keep unable to access the base endpoints. Could someone help me? Or tell me if it is a bug in the package.

PS. Well done on what you've been doing in this library!

**Comment by kevin-carroll** [comment]
Hey @sergiocbueno ,

Thank you so much for the detailed write up. I was able to reproduce the error.   You've done everything right in your screenshots, it should be working exactly as you're expecting.

This is most definitely a bug.   I'll have a fix out this weekend for it.

Cheers,
Kevin
