### ISSUE TITLE
Exposing requested fields for eager loading

### ISSUE THREAD

**Issue by pnwcc** [graphql-aspnet/graphql-aspnet#159]
Hello,

I have an EF Core model with a couple of child collections and child reference objects. Currently, I have to eagerly load each field/collection inside all of my 'Get' actions in order to be able to access those objects with any query:

```csharp
var items = ctx.Bakery
    .Include(b => b.Jellies)
    .Include(b => b.Jams);
```

Only a few queries need these collections though, and I'd prefer if I could instead only eagerly load them if I knew they had been requested. The documentation does mention using EF Core lazy loading proxies, but I'd like to avoid them if possible as I have quite a few collections in my model, and want to keep the requests to the DB low. I could make separate actions for requesting full/partial entities, but would prefer not to need to have nearly identical DTO's in my schema for that.

Is there a way for an action in a `GraphController` to get the field names or DTO properties the client requested from it?

**Comment by MilanLochovsky** [comment]
I'm using this construction:

```csharp
public class TestController : GraphController
{
   public class TestObject
   {
      public string? Text { get; set; }
      public int? Number { get; set; }
   }
   
   [QueryRoot("Test")]
   public TestObject Test()
   {
      var isTextRequested = this.Request.InvocationContext.ChildContexts.Any(s =>
         s.Name.Equals(nameof(TestObject.Text), StringComparison.InvariantCultureIgnoreCase));
      
      var isNumberRequested = this.Request.InvocationContext.ChildContexts.Any(s =>
         s.Name.Equals(nameof(TestObject.Number), StringComparison.InvariantCultureIgnoreCase));

      return new TestObject
      {
         Text = isTextRequested ? "Text" : null,
         Number = isNumberRequested ? 1 : null
      };
   }
}
```

**Comment by pnwcc** [comment]
Works great, thanks! I'm newish to ASP.NET so `Request` wasn't on my radar.
