### ISSUE TITLE
How to perform service registration in a .NET 8 project with a Startup file?

### ISSUE THREAD

**Issue by WarlockZhang** [graphql-aspnet/graphql-aspnet#160]
I added services.AddGraphQL(); in ConfigureServices and app.UseGraphQL(); in Configure, but it didn't work.
![d33a0ac648832056dff5bdbbbceea84b](https://github.com/graphql-aspnet/graphql-aspnet/assets/143587015/ec7ee1f0-a7cd-4c3d-ba27-bd3ac98e9f9b)

**Comment by kevin-carroll** [comment]
Hey @WarlockZhang,

Unfortunately a screenshot of your graphql tool won't be enough to help troubleshoot.

Can you post your code, launch settings (if launching from an IDE) and/or console or web server output when the server starts.  

Your tooling indicates it can't reach the server which could be a number of things that may or may not be related to the configuration of graphql.  Happy to help work through this with you but I need more info to help out.

Cheers,
Kevin
