### ISSUE TITLE
Format schema?

### ISSUE THREAD

**Issue by ropez** [graphql-aspnet/graphql-aspnet#165]
Given a loaded schema, as an instance of the `GraphSchema` type, does this library include a method to format/print it in something like the graphql file format? It's for debugging purposes.

**Comment by kevin-carroll** [comment]
Hey @ropez ,

Currently, no there is no way to do that. The underpinnings are there for it, but its not fully fleshed out or exposed. Internally we build parts of the schema syntax for generating appropriate default value representations during introspection calls but printing the whole schema as a debug option has never been a requested feature.

You've probably thought of this and it may not fit your use case, especially if your automating something, but a lot of people use the myriad of tools out there (graphiql, altair etc.)  that will easily build out the schema syntax from introspection data they fetch from your server.

Happy to add it as a feature request to the backlog!
Kevin

**Comment by ropez** [comment]
Actually, I implemented a formatter quite easily, just iterating over Know types, and printing names, fields, type expressions etc.
