### ISSUE TITLE
Not getting HttpContext in Query or Mutation

### ISSUE THREAD

**Issue by Pramod-Singh-30057234** [graphql-aspnet/graphql-aspnet#37]
Hi Team,

I am trying to identify client IP but HttpContext is not getting. Below is a line of code.
Controller:

 public class AuthGraphController : GraphController
    {       
        [MutationRoot("token")]
        public string Token(LoginModel model)
        {
           var IP=HttpContext?.Connection.RemoteIpAddress.ToString();
           return IP;
        }
    }

Model:
 public class LoginModel
    {
        [Required(ErrorMessage = "User Name is required")]
        public string Username { get; set; }

        [Required(ErrorMessage = "Password is required")]
        public string Password { get; set; }
    }
Please suggest if there is any alternate approach.

**Comment by kevin-carroll** [comment]
The HttpContext is now directly accessible on the controller with the release of `v0.8.0-beta`

```csharp
// controller
public class AuthGraphController : GraphController
{        
       [MutationRoot("token")]
        public string Token(LoginModel model)
        {
              var IP=   this.HttpContext.Connection.RemoteIpAddress.ToString();
              return IP;
        }
}
```

Please let me know if you encounter any issues.

Cheers,
Kevin
