### ISSUE TITLE
Missing __DirectiveLocation options

### ISSUE THREAD

**Issue by skayred** [graphql-aspnet/graphql-aspnet#38]
Hello,

I have recently found that excellent project, but I have a problem of implementation the directive. I have followed the docs and implemented sample directive, which is visible in a schema, but how do I apply it to the certain query?

The result I would like to have:
`
type Query {
  sampleQuery: [String] @sampleDir
}
`

Is it possible to have something like this in schema?

**Comment by kevin-carroll** [comment]
Support for Type system directives and all missing `__DirectiveLocation` values was added with `v0.10.0-beta`

See the [updated documentation](https://graphql-aspnet.github.io/docs/advanced/directives) for how to declare and use all directive types.
