### ISSUE TITLE
Scoped Controllers causing a Race Condition in Ef Core DbContext

### ISSUE THREAD

**Issue by NicolaiJee** [graphql-aspnet/graphql-aspnet#43]
Hi
I really appreciate this library and the concept of it.
I have a small challenge.
I try to perform this query:
`# Write your query or mutation here
query {
  
  vendor{
    loadAll{id name}
    loadById(id: "a07a864d-77a6-44a7-a3d8-20e21e1d8887") {
      name
      id
    }
  }
}`
But only the second operation gets a result, the first one is always null

The code for the 2 operations looks like this and both endpoints are hit and returns data:
` [Query]
        public async Task<Vendor?> LoadById(Guid id)
        {
            var data = await _vendorService.LoadById(id);
            return data != null ? new Vendor(data) : null;
        }

        [Query]
        public async Task<IEnumerable<Vendor>> LoadAll()
        {
            var data = await _vendorService.LoadAll();
            return data != null ? data.Select(m=> new Vendor(m)) : Array.Empty<Vendor>();
        }`

The result always looks like this:
`{
  "data": {
    "vendor": {
      "loadAll": null,
      "loadById": {
        "name": "KlostergadeCentret",
        "id": "a07a864d-77a6-44a7-a3d8-20e21e1d8887"
      }
    }
  }
}`

Am i doing something wrong or is this a limit in the current version ?
I am using the newest one.

**Comment by kevin-carroll** [comment]
With the release of `v0.8.0-beta` all controllers are now registered as `Transient` by default.  This should clear up all the issues you were seeing. You should no longer need to set `AwaitEachRequestedField`.

A new page was added to the documentation for [Entity Framework](https://graphql-aspnet.github.io/docs/development/entity-framework) that details other potential approaches to the ef conumdrum as well.

Please let me know if you have any issues.

Cheers,
Kevin

**Comment by NicolaiJee** [comment]
That is perfect, thank you :)
