### ISSUE TITLE
Is this still being developed ?

### ISSUE THREAD

**Issue by NicolaiJee** [graphql-aspnet/graphql-aspnet#61]
Hi
I wish to use this for a new project, but I am unsure if it will move out of beta and into rtm ?

**Comment by kevin-carroll** [comment]
Hi @NicolaiJee ,

Yes this library is still in active development. I can understand why you'd be curious though. Q1 and Q2 are a busy time of year for me so there hasn't been a lot of progress recently. This should change as we move into the summer months and my free time can turn back toward completing this project.  It will, for sure, move out of beta and into 1.0 release. The only thing that will stop that is my death...and lets hope that doesn't happen. :) 

As a side note, before you consider using this library for a "real" project, please bear in mind the following:

* This is currently a passion project of mine. There is no corporate sponsor or backing of any major company. While I hope that will change we must be realistic and expect that it will never be "mainstream". GraphqlDotnet or hot chocolate are better choices and less risk for any business workloads right now for any projects of a decent scale. 
  * While I have faith in this library and expect it to be fully competitive when it gets to 1.0 status there is risk in choosing to implement this library right now.
* I am the only contributor to this project and I work a full time job. There is only so much time that can be dedicated to moving things forward.
* Its not battle tested yet, there may be some risk in using this library in a production environment. I would be more than happy to collaborate with you to address any issues should you choose to take that risk, but it is a risk nonetheless.
* I can offer no exact date of with 1.0 status would be achieved. I have a goal of this year (2022) but nothing set in stone. If work or family pulls me away then that timeline will be delayed.

Cheers, 
KC

**Comment by NicolaiJee** [comment]
Hi Kevin
Good to hear, I really like this project and I am monitoring it regularly :)
I completely understand you points, and I am glad you are honest.
I will use this project if I have a less business critical project.

Sadly my situation is much like yours, so I can't really help with the development of this :/
