### ISSUE TITLE
HTTP GET support and query url param

### ISSUE THREAD

**Issue by pmoleri** [graphql-aspnet/graphql-aspnet#80]
The [GraphQL recommendation](https://graphql.org/learn/serving-over-http/#http-methods-headers-and-body) is to support both GET and POST.

But when trying GET on `graphql-aspnet` it's throwing error:
> GraphQL queries should be executed as a POST request

Even when using POST, there's a recommendation of accepting the `query` parameter from the URL query string, like:
`http://myapi/graphql?query={me{name}}`

attempting this it also fails trying to parse the body.

**Comment by kevin-carroll** [comment]
Thanks @pmoleri  !

Confirmed bug. `DefaultGraphQLHttpProcessor` does not currently support `GET` requests.

**Comment by pmoleri** [comment]
I tried and works great.
e.g. `http://localhost:5000/graphql?query={ droids { search() { id, name, primaryFunction } } }`
