### ISSUE TITLE
Can't find the package for .net core with controller

### ISSUE THREAD

**Issue by krisrajzlive** [graphql-aspnet/graphql-aspnet#86]
I have installed GraphQl Asp.Net Core package but can't find GraphController and Attributes for ASP.Net Core application. May I know whether ASP.Net Core is not supported?

**Comment by kevin-carroll** [comment]
Hi @krisrajzlive ,

**Yes**, the library supports `netcoreapp3.1` and `net6.0`  (net5.0 was retired May, [per microsoft](https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core)).

Without seeing a code example or knowing more about your project setup its tough to diagnose the issue.  

Please make sure that you have the correct using statements at the top of your controller class. 

```csharp

// Other using statements, depending on your needs
using System;

// ******************************************************
// Make sure you include these two using statements
// ******************************************************
using GraphQL.AspNet.Attributes;
using GraphQL.AspNet.Controllers;

namespace MyExampleProject
{
    public class BakeryController: GraphController
    {
        [Query("search")]
        public async Task<IEnumerable<Donut>> SearchDonuts(string searchText = "*")
        {
              /* ... */
        }
    }
}
```

If you wanted to look at the source files to see their namespaces, they are here:

Source Code: [GraphController.cs](https://github.com/graphql-aspnet/graphql-aspnet/blob/master/src/graphql-aspnet/Controllers/GraphController.cs)
Source Code: [All Attributes](https://github.com/graphql-aspnet/graphql-aspnet/tree/master/src/graphql-aspnet/Attributes)

**Comment by krisrajzlive** [comment]
I am trying to create a web api project either in .net or .net core but was never able to add a reference to GraphQl.AspNet.Controllers though I have added the package successfully. 

I tried both on .Net Core 3.1 and .Net 6. I may be missing something, Can you share me any article link on how I can create GraphQl project as in .Net Core 3.1.

**Comment by kevin-carroll** [comment]
If you have this package reference in your csproj file, thats all you need (unless you want to add subscriptions):
`<PackageReference Include="GraphQL.AspNet" Version="0.12.2-beta" />`

The [quick start guide](https://graphql-aspnet.github.io/docs/quick/quick-start) might be a good place to start. It mentions using an `ASP.NET MVC Project` but the steps are nearly identical for  a web api project.  

A word of warning, the quick start guide is pending an update as Microsoft has moved away from using the `startup.cs`, so you may need to make some adjustments for that.  

Alternatively, here is a very simple sample project that may help written in .net core 3.1 (using startup.cs) and .NET 6 (without startup.cs):
https://github.com/kevin-carroll/graphql-aspnet-86

Also here are all the [official sample projects](https://graphql-aspnet.github.io/docs/reference/demo-projects) that go through various features if you want to look at more examples. They are much more complex and may not be a good starting point for you.

Hope this helps,
Kevin

**Comment by krisrajzlive** [comment]
I have cloned https://github.com/kevin-carroll/graphql-aspnet-86 and ran both .Net Core 3.1 and .Net 6 and I keep on getting "No query received on the request" upon hitting the url http://localhost:5000/graphql (have also tried https with no respite) And, this is the console:

info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://localhost:5000
dbug: Microsoft.AspNetCore.Hosting.Diagnostics[13]
      Loaded hosting startup assembly sample-project-net60
dbug: Microsoft.AspNetCore.Hosting.Diagnostics[13]
      Loaded hosting startup assembly Microsoft.AspNetCore.Watch.BrowserRefresh
dbug: Microsoft.AspNetCore.Hosting.Diagnostics[13]
      Loaded hosting startup assembly Microsoft.WebTools.BrowserLink.Net
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]
      Content root path: C:\Users\KrishnamuR\source\repos\graphql-aspnet-86\net60\sample-project-net60\sample-project-net60\
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET http://localhost:5000/graphql - -
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/1.1 GET http://localhost:5000/graphql - - - 400 - - 119.9598ms

Am I missing anything?

**Comment by krisrajzlive** [comment]
Awesome thanks, it works!

How can I inject any playground ide?

**Comment by krisrajzlive** [comment]
Appreciate all your help! :)
I am trying to call a method that just returns a string as below:
graphql?query=query{addl}
graphql?query={addl}
graphql?query=query{addl{}}

Always getting the error message:
The graph type 'Query' does not contain a field named 'addl'.

Any help would be much appreciated.

Thanks

**Comment by krisrajzlive** [comment]
Also, I tried a method to return an object and got the same issue. It looks like the package expects all methods to return IEnumerable?!

**Comment by kevin-carroll** [comment]
Use of any of the playground IDEs are not related this library. Most of them are as simple as typing in the appropriate URL when prompted.  There is nothing special that you need to do to configure your project to work them. 

--

The error message `The graph type 'Query' does not contain a field named 'addl'` indicates that your method isn't part of the graph, or at least its not registered at a location indicated by your query. Make sure you register your methods properly using the appropriate `[Query]` or `[QueryRoot]` attributes.  They work similarly to `[HttpGet]`.  

More info on setting up controllers is [here](https://graphql-aspnet.github.io/docs/controllers/actions) and a reference list of all the various attributes are [here](https://graphql-aspnet.github.io/docs/reference/attributes#mutation-mutationroot-query-queryroot)

--

No, the package does not expect all methods to return an `IEnumerable`, that would be very limiting.  Unfortunately, without seeing your code, I can't offer any opinions on what your issues might be.

Hope this helps,
Kevin

**Comment by krisrajzlive** [comment]
I have a Settings class with 3 attributes and I have a method to return each of these attributes as I don't want to return all of the settings class attributes. Each of these method returns only string. Please let me know is there anything.

``
    public class Settings
    {
        public string SystemSecurityDBConnection { get; set; }
        public string ADDL { get; set; }
        public string ExcludeAD { get; set; }
    }

public class AppConfigController : GraphController
    {
        private readonly Settings _settings;
 
        public AppConfigController(IOptionsSnapshot<Settings> settings)
        {
            _settings = settings.Value;
        }

        [Query("systemSecuritydbconnection")]
        public async Task<string> GetSystemSecurityDBConnection()
        {
             return _settings.SystemSecurityDBConnection;
        }

        [Query("addl")]
        public async Task<string> GetADDL()
        {
            return _settings.ADDL;
        }

        [Query("excludead")]
        public async Task<string> GetExcludeAD()
        {
            return _settings.ExcludeAD;
        }

**Comment by krisrajzlive** [comment]
I have figured out myself:

http://localhost:5000/graphql?query=query{appConfig{addl%20excludead%20systemSecuritydbconnection}}

where, appConfig is the name of the Controller

This is awesome, makes GraphQL API simpler and saved lots of time. Kudos to you for your patience!

**Comment by kevin-carroll** [comment]
Fantastic! Glad to hear you got things sorted.

Cheers,
Kevin
