### ISSUE TITLE
How to set nullable Guid?

### ISSUE THREAD

**Issue by yozawiratama** [graphql-aspnet/graphql-aspnet#95]
I already create Model with nullable guid like this

```c#
public class MyModel {
  public Guid? MyID {get; set;}
}
```

and I place it as parameter

```c#
[MutationRoot("createSalesOrder", typeof(Response<Guid>))]
    public async Task<IGraphActionResult> Create(MyModel param)
    {
        return Ok(new Response<Guid>(Guid.NewGuid(), "Success"));
    }
```

and this is my mutation:

```graphql
mutation SalesCreate($myId Guid){
   createSalesOrder(param : {myId: $myId}){
       data,
       error
   }
}
```

and I tried with empty variable `{}` or `{myId: null}`

but I get this error:
```json
{
  "errors": [
    {
      "message": "The value '\"\"' cannot be coerced or resolved for the target location (System Type: Guid).",
      "locations": [
        {
          "line": 1,
          "column": 1
        }
      ],
      "extensions": {
        "code": "INVALID_VARIABLE_VALUE",
        "timestamp": "2022-12-28T05:15:13.836+07:00",
        "severity": "CRITICAL"
      }
    }
  ]
}
```

so how to set nullable Guid properly?

**Comment by kevin-carroll** [comment]
Hi @yozawiratama ,

Thank you for the detailed write up. You're doing everything correctly. 

This appears to be a bug with the variable generator.  I was able to reproduce the issue exactly as you've stated.  I'll have a fix out with RC3 this weekend.

Cheers,
Kevin

**Comment by yozawiratama** [comment]
Hi @kevin-carroll

 I really feel helped by this library

Can't wait next update,

Thank you

🙏
